create function public.normalize_vocabulary_word(
  input_word text,
  input_source_language text
)
returns text
language plpgsql
stable
strict
set search_path = ''
as $$
declare
  -- Generated by Node.js 24 / Unicode 17.0 from ECMAScript \\p{M}.
  -- PostgreSQL 17 regular expressions do not expose Unicode general categories.
  mark_code_points constant int4multirange := '{
    [768,880),
    [1155,1162),
    [1425,1470),
    [1471,1472),
    [1473,1475),
    [1476,1478),
    [1479,1480),
    [1552,1563),
    [1611,1632),
    [1648,1649),
    [1750,1757),
    [1759,1765),
    [1767,1769),
    [1770,1774),
    [1809,1810),
    [1840,1867),
    [1958,1969),
    [2027,2036),
    [2045,2046),
    [2070,2074),
    [2075,2084),
    [2085,2088),
    [2089,2094),
    [2137,2140),
    [2199,2208),
    [2250,2274),
    [2275,2308),
    [2362,2365),
    [2366,2384),
    [2385,2392),
    [2402,2404),
    [2433,2436),
    [2492,2493),
    [2494,2501),
    [2503,2505),
    [2507,2510),
    [2519,2520),
    [2530,2532),
    [2558,2559),
    [2561,2564),
    [2620,2621),
    [2622,2627),
    [2631,2633),
    [2635,2638),
    [2641,2642),
    [2672,2674),
    [2677,2678),
    [2689,2692),
    [2748,2749),
    [2750,2758),
    [2759,2762),
    [2763,2766),
    [2786,2788),
    [2810,2816),
    [2817,2820),
    [2876,2877),
    [2878,2885),
    [2887,2889),
    [2891,2894),
    [2901,2904),
    [2914,2916),
    [2946,2947),
    [3006,3011),
    [3014,3017),
    [3018,3022),
    [3031,3032),
    [3072,3077),
    [3132,3133),
    [3134,3141),
    [3142,3145),
    [3146,3150),
    [3157,3159),
    [3170,3172),
    [3201,3204),
    [3260,3261),
    [3262,3269),
    [3270,3273),
    [3274,3278),
    [3285,3287),
    [3298,3300),
    [3315,3316),
    [3328,3332),
    [3387,3389),
    [3390,3397),
    [3398,3401),
    [3402,3406),
    [3415,3416),
    [3426,3428),
    [3457,3460),
    [3530,3531),
    [3535,3541),
    [3542,3543),
    [3544,3552),
    [3570,3572),
    [3633,3634),
    [3636,3643),
    [3655,3663),
    [3761,3762),
    [3764,3773),
    [3784,3791),
    [3864,3866),
    [3893,3894),
    [3895,3896),
    [3897,3898),
    [3902,3904),
    [3953,3973),
    [3974,3976),
    [3981,3992),
    [3993,4029),
    [4038,4039),
    [4139,4159),
    [4182,4186),
    [4190,4193),
    [4194,4197),
    [4199,4206),
    [4209,4213),
    [4226,4238),
    [4239,4240),
    [4250,4254),
    [4957,4960),
    [5906,5910),
    [5938,5941),
    [5970,5972),
    [6002,6004),
    [6068,6100),
    [6109,6110),
    [6155,6158),
    [6159,6160),
    [6277,6279),
    [6313,6314),
    [6432,6444),
    [6448,6460),
    [6679,6684),
    [6741,6751),
    [6752,6781),
    [6783,6784),
    [6832,6878),
    [6880,6892),
    [6912,6917),
    [6964,6981),
    [7019,7028),
    [7040,7043),
    [7073,7086),
    [7142,7156),
    [7204,7224),
    [7376,7379),
    [7380,7401),
    [7405,7406),
    [7412,7413),
    [7415,7418),
    [7616,7680),
    [8400,8433),
    [11503,11506),
    [11647,11648),
    [11744,11776),
    [12330,12336),
    [12441,12443),
    [42607,42611),
    [42612,42622),
    [42654,42656),
    [42736,42738),
    [43010,43011),
    [43014,43015),
    [43019,43020),
    [43043,43048),
    [43052,43053),
    [43136,43138),
    [43188,43206),
    [43232,43250),
    [43263,43264),
    [43302,43310),
    [43335,43348),
    [43392,43396),
    [43443,43457),
    [43493,43494),
    [43561,43575),
    [43587,43588),
    [43596,43598),
    [43643,43646),
    [43696,43697),
    [43698,43701),
    [43703,43705),
    [43710,43712),
    [43713,43714),
    [43755,43760),
    [43765,43767),
    [44003,44011),
    [44012,44014),
    [64286,64287),
    [65024,65040),
    [65056,65072),
    [66045,66046),
    [66272,66273),
    [66422,66427),
    [68097,68100),
    [68101,68103),
    [68108,68112),
    [68152,68155),
    [68159,68160),
    [68325,68327),
    [68900,68904),
    [68969,68974),
    [69291,69293),
    [69370,69376),
    [69446,69457),
    [69506,69510),
    [69632,69635),
    [69688,69703),
    [69744,69745),
    [69747,69749),
    [69759,69763),
    [69808,69819),
    [69826,69827),
    [69888,69891),
    [69927,69941),
    [69957,69959),
    [70003,70004),
    [70016,70019),
    [70067,70081),
    [70089,70093),
    [70094,70096),
    [70188,70200),
    [70206,70207),
    [70209,70210),
    [70367,70379),
    [70400,70404),
    [70459,70461),
    [70462,70469),
    [70471,70473),
    [70475,70478),
    [70487,70488),
    [70498,70500),
    [70502,70509),
    [70512,70517),
    [70584,70593),
    [70594,70595),
    [70597,70598),
    [70599,70603),
    [70604,70609),
    [70610,70611),
    [70625,70627),
    [70709,70727),
    [70750,70751),
    [70832,70852),
    [71087,71094),
    [71096,71105),
    [71132,71134),
    [71216,71233),
    [71339,71352),
    [71453,71468),
    [71724,71739),
    [71984,71990),
    [71991,71993),
    [71995,71999),
    [72000,72001),
    [72002,72004),
    [72145,72152),
    [72154,72161),
    [72164,72165),
    [72193,72203),
    [72243,72250),
    [72251,72255),
    [72263,72264),
    [72273,72284),
    [72330,72346),
    [72544,72552),
    [72751,72759),
    [72760,72768),
    [72850,72872),
    [72873,72887),
    [73009,73015),
    [73018,73019),
    [73020,73022),
    [73023,73030),
    [73031,73032),
    [73098,73103),
    [73104,73106),
    [73107,73112),
    [73459,73463),
    [73472,73474),
    [73475,73476),
    [73524,73531),
    [73534,73539),
    [73562,73563),
    [78912,78913),
    [78919,78934),
    [90398,90416),
    [92912,92917),
    [92976,92983),
    [94031,94032),
    [94033,94088),
    [94095,94099),
    [94180,94181),
    [94192,94194),
    [113821,113823),
    [118528,118574),
    [118576,118599),
    [119141,119146),
    [119149,119155),
    [119163,119171),
    [119173,119180),
    [119210,119214),
    [119362,119365),
    [121344,121399),
    [121403,121453),
    [121461,121462),
    [121476,121477),
    [121499,121504),
    [121505,121520),
    [122880,122887),
    [122888,122905),
    [122907,122914),
    [122915,122917),
    [122918,122923),
    [123023,123024),
    [123184,123191),
    [123566,123567),
    [123628,123632),
    [124140,124144),
    [124398,124400),
    [124643,124644),
    [124646,124647),
    [124654,124656),
    [124661,124662),
    [125136,125143),
    [125252,125259),
    [917760,918000)
  }'::int4multirange;
  -- Generated by Node.js 24 / Unicode 17.0 from ECMAScript \\p{N}.
  -- POSIX [:alnum:] does not include every Unicode number category.
  number_code_points constant int4multirange := '{
    [48,58),
    [178,180),
    [185,186),
    [188,191),
    [1632,1642),
    [1776,1786),
    [1984,1994),
    [2406,2416),
    [2534,2544),
    [2548,2554),
    [2662,2672),
    [2790,2800),
    [2918,2928),
    [2930,2936),
    [3046,3059),
    [3174,3184),
    [3192,3199),
    [3302,3312),
    [3416,3423),
    [3430,3449),
    [3558,3568),
    [3664,3674),
    [3792,3802),
    [3872,3892),
    [4160,4170),
    [4240,4250),
    [4969,4989),
    [5870,5873),
    [6112,6122),
    [6128,6138),
    [6160,6170),
    [6470,6480),
    [6608,6619),
    [6784,6794),
    [6800,6810),
    [6992,7002),
    [7088,7098),
    [7232,7242),
    [7248,7258),
    [8304,8305),
    [8308,8314),
    [8320,8330),
    [8528,8579),
    [8581,8586),
    [9312,9372),
    [9450,9472),
    [10102,10132),
    [11517,11518),
    [12295,12296),
    [12321,12330),
    [12344,12347),
    [12690,12694),
    [12832,12842),
    [12872,12880),
    [12881,12896),
    [12928,12938),
    [12977,12992),
    [42528,42538),
    [42726,42736),
    [43056,43062),
    [43216,43226),
    [43264,43274),
    [43472,43482),
    [43504,43514),
    [43600,43610),
    [44016,44026),
    [65296,65306),
    [65799,65844),
    [65856,65913),
    [65930,65932),
    [66273,66300),
    [66336,66340),
    [66369,66370),
    [66378,66379),
    [66513,66518),
    [66720,66730),
    [67672,67680),
    [67705,67712),
    [67751,67760),
    [67835,67840),
    [67862,67868),
    [68028,68030),
    [68032,68048),
    [68050,68096),
    [68160,68169),
    [68221,68223),
    [68253,68256),
    [68331,68336),
    [68440,68448),
    [68472,68480),
    [68521,68528),
    [68858,68864),
    [68912,68922),
    [68928,68938),
    [69216,69247),
    [69405,69415),
    [69457,69461),
    [69573,69580),
    [69714,69744),
    [69872,69882),
    [69942,69952),
    [70096,70106),
    [70113,70133),
    [70384,70394),
    [70736,70746),
    [70864,70874),
    [71248,71258),
    [71360,71370),
    [71376,71396),
    [71472,71484),
    [71904,71923),
    [72016,72026),
    [72688,72698),
    [72784,72813),
    [73040,73050),
    [73120,73130),
    [73184,73194),
    [73552,73562),
    [73664,73685),
    [74752,74863),
    [90416,90426),
    [92768,92778),
    [92864,92874),
    [93008,93018),
    [93019,93026),
    [93552,93562),
    [93824,93847),
    [94196,94199),
    [118000,118010),
    [119488,119508),
    [119520,119540),
    [119648,119673),
    [120782,120832),
    [123200,123210),
    [123632,123642),
    [124144,124154),
    [124401,124411),
    [125127,125136),
    [125264,125274),
    [126065,126124),
    [126125,126128),
    [126129,126133),
    [126209,126254),
    [126255,126270),
    [127232,127245),
    [130032,130042)
  }'::int4multirange;
  characters text[];
  collation_name name;
  end_index integer;
  normalized_word text;
  primary_language text;
  start_index integer := 1;
begin
  normalized_word := normalize(pg_catalog.btrim(input_word), NFKC);
  -- PostgreSQL 17 uses Unicode 15.1 normalization data, while Node.js 24 uses
  -- Unicode 17.0. These are all compatibility mappings added since 15.1.
  normalized_word := pg_catalog.translate(
    normalized_word,
    U&'\A7F1\+01CCD6\+01CCD7\+01CCD8\+01CCD9\+01CCDA\+01CCDB\+01CCDC\+01CCDD\+01CCDE\+01CCDF\+01CCE0\+01CCE1\+01CCE2\+01CCE3\+01CCE4\+01CCE5\+01CCE6\+01CCE7\+01CCE8\+01CCE9\+01CCEA\+01CCEB\+01CCEC\+01CCED\+01CCEE\+01CCEF\+01CCF0\+01CCF1\+01CCF2\+01CCF3\+01CCF4\+01CCF5\+01CCF6\+01CCF7\+01CCF8\+01CCF9',
    'SABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  );
  normalized_word := pg_catalog.translate(
    normalized_word,
    U&'\2018\2019\02BC',
    U&'\0027\0027\0027'
  );
  primary_language := pg_catalog.split_part(
    pg_catalog.lower(pg_catalog.btrim(input_source_language)),
    '-',
    1
  );

  select collations.collname
  into collation_name
  from pg_catalog.pg_collation as collations
  where collations.collprovider = 'i'
    and collations.collname = primary_language || '-x-icu'
  limit 1;

  if collation_name is null then
    collation_name := 'und-x-icu';
  end if;

  execute pg_catalog.format(
    'select pg_catalog.lower($1 collate pg_catalog.%I)',
    collation_name
  )
  into normalized_word
  using normalized_word;

  characters := pg_catalog.string_to_array(normalized_word, null);
  end_index := pg_catalog.cardinality(characters);

  while start_index <= end_index
    and not (
      characters[start_index] ~ '[[:alnum:]]'
      or pg_catalog.ascii(characters[start_index]) <@ mark_code_points
      or pg_catalog.ascii(characters[start_index]) <@ number_code_points
    )
  loop
    start_index := start_index + 1;
  end loop;

  while end_index >= start_index
    and not (
      characters[end_index] ~ '[[:alnum:]]'
      or pg_catalog.ascii(characters[end_index]) <@ mark_code_points
      or pg_catalog.ascii(characters[end_index]) <@ number_code_points
    )
  loop
    end_index := end_index - 1;
  end loop;

  normalized_word := pg_catalog.array_to_string(
    characters[start_index:end_index],
    ''
  );

  return normalize(normalized_word, NFC);
end;
$$;

revoke execute
on function public.normalize_vocabulary_word(text, text)
from public, anon;

grant execute
on function public.normalize_vocabulary_word(text, text)
to authenticated, service_role;

-- Hold one write boundary from the backfill snapshot through trigger creation.
lock table public.vocabulary_cards in share row exclusive mode;

create temporary table vocabulary_card_normalization_plan
on commit drop
as
with normalized_cards as (
  select
    cards.*,
    public.normalize_vocabulary_word(
      cards.word,
      cards.source_language
    ) as normalized_word
  from public.vocabulary_cards as cards
)
select
  normalized_cards.id,
  normalized_cards.normalized_word,
  pg_catalog.first_value(normalized_cards.id) over card_group as survivor_id,
  pg_catalog.row_number() over card_group as card_priority,
  pg_catalog.count(*) over card_group as card_count,
  pg_catalog.min(normalized_cards.created_at) over card_group as earliest_created_at
from normalized_cards
window card_group as (
  partition by
    normalized_cards.user_id,
    normalized_cards.source_language,
    normalized_cards.target_language,
    normalized_cards.normalized_word
  order by
    normalized_cards.updated_at desc,
    normalized_cards.created_at desc,
    normalized_cards.id desc
  rows between unbounded preceding and unbounded following
);

do $$
begin
  if exists (
    select 1
    from vocabulary_card_normalization_plan as normalization_plan
    where normalization_plan.normalized_word = ''
  ) then
    raise exception using
      errcode = '23514',
      message = 'A vocabulary card cannot normalize to an empty word.';
  end if;

end;
$$;

create temporary table vocabulary_card_merged_translations
on commit drop
as
select
  meanings_by_key.survivor_id,
  pg_catalog.array_agg(
    meanings_by_key.display_value
    order by
      meanings_by_key.first_card_priority,
      meanings_by_key.first_position
  ) as translation
from (
  select
    normalization_plan.survivor_id,
    (
      pg_catalog.array_agg(
        pg_catalog.btrim(meanings.value)
        order by normalization_plan.card_priority, meanings.position
      )
    )[1] as display_value,
    pg_catalog.min(normalization_plan.card_priority) as first_card_priority,
    (
      pg_catalog.array_agg(
        meanings.position
        order by normalization_plan.card_priority, meanings.position
      )
    )[1] as first_position
  from vocabulary_card_normalization_plan as normalization_plan
  join public.vocabulary_cards as cards
    on cards.id = normalization_plan.id
  cross join lateral pg_catalog.unnest(cards.translation)
    with ordinality as meanings(value, position)
  group by
    normalization_plan.survivor_id,
    pg_catalog.lower(pg_catalog.btrim(meanings.value))
) as meanings_by_key
group by meanings_by_key.survivor_id;

do $$
begin
  if exists (
    select 1
    from vocabulary_card_normalization_plan as normalization_plan
    join public.vocabulary_cards as cards
      on cards.id = normalization_plan.survivor_id
    join vocabulary_card_merged_translations as merged_translations
      on merged_translations.survivor_id = normalization_plan.survivor_id
    where normalization_plan.id = normalization_plan.survivor_id
      and pg_catalog.cardinality(merged_translations.translation) > 10
      and (
        normalization_plan.card_count > 1
        or cards.word is distinct from normalization_plan.normalized_word
        or cards.translation is distinct from merged_translations.translation
        or cards.created_at is distinct from normalization_plan.earliest_created_at
      )
  ) then
    raise exception using
      errcode = '23514',
      message = 'Normalized vocabulary card duplicates exceed the ten-meaning limit.';
  end if;
end;
$$;

delete from public.vocabulary_cards as cards
using vocabulary_card_normalization_plan as normalization_plan
where cards.id = normalization_plan.id
  and normalization_plan.id <> normalization_plan.survivor_id;

update public.vocabulary_cards as cards
set
  word = normalization_plan.normalized_word,
  translation = merged_translations.translation,
  created_at = normalization_plan.earliest_created_at
from vocabulary_card_normalization_plan as normalization_plan
join vocabulary_card_merged_translations as merged_translations
  on merged_translations.survivor_id = normalization_plan.survivor_id
where cards.id = normalization_plan.survivor_id
  and normalization_plan.id = normalization_plan.survivor_id
  and (
    cards.word is distinct from normalization_plan.normalized_word
    or cards.translation is distinct from merged_translations.translation
    or cards.created_at is distinct from normalization_plan.earliest_created_at
  );

create function public.normalize_vocabulary_card_word()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.word := public.normalize_vocabulary_word(
    new.word,
    new.source_language
  );

  return new;
end;
$$;

revoke execute
on function public.normalize_vocabulary_card_word()
from public;

create trigger vocabulary_cards_normalize_word
before insert or update of word, source_language
on public.vocabulary_cards
for each row
execute function public.normalize_vocabulary_card_word();
